export {
  allNonSteamGames,
  applyMetadata,
  applyCompatibilityDefault,
  beginCompatibilityLifecycle,
  cancelCompatibilityDefaultLoad,
  ensureCompatibilityDefault,
  effectiveCompatibilityCategory,
  ensureMetadataCache,
  flushDeferredCompatibilityPublications,
  refreshMetadataCache,
  refreshCompatibilitySurfaces,
  retainCompatibilityBaselinesForReload,
  restoreAllCompatibilityBaselines,
  setConfirmedCompatibilityDefault,
  startMetadataBootstrap,
  tryEnrichScreenshotsForApp,
  tryFetchMetadataForApp,
} from "./steam/metadataPatch";
export {
  formatConnectedControllerTypes,
  getConnectedControllerTypes,
} from "./steam/controllerTypes";
export {
  appName,
  compatibilityDefaultLoadedSnapshot,
  compatibilityDefaultSnapshot,
  compatibilityLifecycleSnapshot,
  compatibilityRevisionSnapshot,
  cleanTitle,
  getOverview,
  getNativeOverview,
  hasActivityStore,
  hasSteamInternals,
  isNonSteamApp,
  isNativeNonSteamShortcut,
  isCompatibilityLifecycleCurrent,
  metadataCache,
  patchInstallStatus,
  rewriteSteamLinkToMatchedApp,
  steamAppIdForApp,
  subscribeCompatibilityRevision,
} from "./steam/core";
export {
  classifyShortcutNameState,
  hasShortcutNameApi,
  nativeShortcutName,
  setShortcutNameAndWait,
} from "./steam/shortcutNames";
export { installSteamPatches } from "./steam/install";
